import { ColorPalette } from '@models';

export const colorPalette: ColorPalette = {
  // Surface
  surface_main: '#FFFFFF',
  surface_main_background: '#FFFFFF',
  surface_main_secondary: '#F6F7F9',
  surface_main_tertiary: '#7E838F',
  surface_main_brand: '#25b79b',
  surface_main_brand_light: '#F9F5FF',
  surface_conditional_negative: '#D0231B',
  surface_conditional_negative_light: '#FBF4F4',
  surface_conditional_info: '#0274C4',
  surface_conditional_info_light: '#F2FAFF',
  surface_conditional_positive: '#1B7F45',
  surface_conditional_positive_light: '#F4FBF7',
  surface_conditional_warning: '#BD5105',
  surface_conditional_warning_light: '#FEF6F1',
  surface_conditional_disable: '#C0C4CC',
  surface_conditional_disable_light: '#EAECF0',
  surface_overlay_100: '#313235',
  surface_overlay_30: '#3132354D',
  surface_overlay_15: '#31323526',
  surface_overlay_8: '#31323514',

  // Content
  content_main_primary: '#313235',
  content_main_secondary: '#7E838F',
  content_main_tertiary: '#C0C4CC',
  content_main_on_tertiary: '#FFFFFF',
  content_main_on_overlay: '#FFFFFF',
  content_main_brand: '#25b79b',
  content_main_on_brand: '#F9F5FF',
  content_main_brand_light: '#F9F5FF',
  content_main_on_brand_light: '#883DF2',
  content_conditional_negative: '#D0231B',
  content_conditional_on_negative: '#FBF4F4',
  content_conditional_negative_light: '#FBF4F4',
  content_conditional_on_negative_light: '#D0231B',
  content_conditional_info: '#0274C4',
  content_conditional_on_info: '#F2FAFF',
  content_conditional_info_light: '#F2FAFF',
  content_conditional_on_info_light: '#0274C4',
  content_conditional_positive: '#1B7F45',
  content_conditional_on_positive: '#F4FBF7',
  content_conditional_positive_light: '#F4FBF7',
  content_conditional_on_positive_light: '#1B7F45',
  content_conditional_warning: '#BD5105',
  content_conditional_on_warning: '#FEF6F1',
  content_conditional_warning_light: '#FEF6F1',
  content_conditional_on_warning_light: '#BD5105',
  content_conditional_disable: '#C0C4CC',
  content_conditional_on_disable: '#FFFFFF',
  content_conditional_on_disable_light: '#C0C4CC',

  // Border
  border_main_primary: '#EAECF0',
  border_main_secondary: '#7E838F',
  border_main_brand: '#25b79b',
  border_main_brand_light: '#F0E6FE',
  border_conditional_negative: '#D0231B',
  border_conditional_negative_light: '#F7E9E8',
  border_conditional_info: '#0274C4',
  border_conditional_info_light: '#E6F4FE',
  border_conditional_positive: '#1B7F45',
  border_conditional_positive_light: '#E9F7EF',
  border_conditional_warning: '#BD5105',
  border_conditional_warnin_light: '#FEF4EB',
  border_conditional_disable: '#C0C4CC',
  border_conditional_disable_light: '#EAECF0',

  // Box Shadows
  sticky_box_shadow: '0px -2px 3px rgba(72, 75, 82, 0.05)',
  gradient_1: 'linear-gradient(266.6deg, #f8f9fb 27.66%, #eaecf0 85.51%)',
  gradient_2:
    'linear-gradient(0deg, rgba(22, 3, 48, 0.34), rgba(22, 3, 48, 0.34))',
  gradient_3: 'linear-gradient(78deg, #f8f9fb 0%, #eaecf0 100%)',
};
